### ISSUE TITLE
Physical quantities should exist in a separate namespace than units

### ISSUE THREAD

**Issue by whitequark** [tiffany352/rink-rs#12]
```
> air density
air: Average molecular weight of air. density = 1 kilogram / meter^3
> gold density
gold: density = 1 kilogram / meter^3
> silver density
silver: density = 1 kilogram / meter^3
```

**Comment by tiffany352** [comment]
Okay, that's pretty bad. It's multiplying air by `density` to make `density` amount of air, and `density` is a physical quantity. The substance printer then prints the amount and uses the quantity name instead of "amount".

The correct query would be using the `of` operator, but it looks like rink doesn't actually know the density of any of those substances.

I need to make physical quantities exist in a separate namespace from regular units. Maybe I could even make it so that multiplying a unit by a quantity works the same as the `of` operator.

**Comment by whitequark** [comment]
Thank you!
