### ISSUE TITLE
input box hidden on rink-web on mobile devices

### ISSUE THREAD

**Issue by whitequark** [tiffany352/rink-rs#5]
rink-web looks like this on my phone:
![screenshot_2016-10-09-18-02-23](https://cloud.githubusercontent.com/assets/54771/19219627/a128a9f0-8e07-11e6-9d82-5d941bb35504.png)

There's no input box. (There's some input because I coped the URL from my desktop.) The hamburger button does nothing. BTW, putting the input box into the header on mobile devices might be a bad idea; e.g. the default Android browser will put the URL box *over* that part of the page.

**Comment by whitequark** [comment]
You should be able to do any testing on a PC using Chromium developer tools (F12 → Shift+Ctrl+M).

**Comment by tiffany352** [comment]
I've fixed the issue for now by including the javascript components of bootstrap, so that the hamburger button works. In the future, I think the input box should possibly go somewhere else like you said.

When I add notebook functionality, I intend the input box to be at the bottom underneath previous queries, for a sort of REPL. The search box should perhaps be front and center on the main page.

**Comment by whitequark** [comment]
Thanks!

> In the future, I think the input box should possibly go somewhere else like you said.

There's no immediate need since browser UI only overlaps the hamburger button, not the input box.
