### ISSUE TITLE
precedence issue

### ISSUE THREAD

**Issue by whitequark** [tiffany352/rink-rs#7]
To reproduce:
```
> 300g/(58 g/mol)
150/29, approx. 5.172413 mole (amount)
> 300g/(58 g/mol)*(22.4 l/mol)
46875/203, approx. 230.9113 mole^2 / meter^3
```

**Comment by tiffany352** [comment]
Division has lower precedence than multiplication, because it seems to be most often the case that that is what was intended. The rule where multiplication and division have equal precedence is unintuitive to some people, but it matches what programming languages do. I feel like precedence issues were much more common before I made it have lower precedence, but it's not like I did A/B testing.

 I have considered making the precedence of multiplication by juxtaposition being higher than both / and *, with / and * having the same precedence. I feel like this would cover more cases of what people expect, but would be even more complicated to learn the rules for. It would mean that for the two operations of multiplication and division, there are three different precedence levels (/ and *, juxtaposition, and |).

An even more complex solution (but perhaps more DWIM?) would be to change the grammar to something like this:
```
unit_powexpr := unit [ ('^'|'**') (<number> | <parenthesized_expr>)]
term := 
    [<number>] {<unit_powexpr>}+ [ '/' {<unit_powexpr>}+] |
    <parenthesized_expr>
mul_expr := 
    term |
    mul_expr '*' term |
    mul_expr '/' term
```
, modulo errors and left recursion.

This would, I believe, allow you to write this:
```
300g / 58g/mol * 22.4l/mol
```

and get the intended result. If I were to go with this scheme, it might be a good idea to make precedence-correct whitespace mandatory.

**Comment by whitequark** [comment]
By the way I think there's also a bug somewhere:
```
> 300g/(58 g/mol)*(22.4 l/mol)
46875/203, approx. 230.9113 mole^2 / meter^3
> 300g/(58 g/mol)/(22.4 l/mol)
93750/406, approx. 230.9113 mole^2 / meter^3
```
... because these two expressions cannot possibly return the same value

**Comment by tiffany352** [comment]
It looks like / has surprising associativity. In the current scheme, I think it should be right associative, but it is currently left associative. I'll make sure to fix that.
```
> 'a'/'b'/'c'
1 a / b c
> ('a'/'b')/'c'
1 a / b c
> 'a'/'b'*'c'
1 a / b c
> 'a'/('b'*'c')
1 a / b c
```

**Comment by tiffany352** [comment]
I've changed the associativity of /, so now it behaves like this:

```
> 'a'/'b'/'c'
1 a c / b
> 'a'/('b'/'c')
1 a c / b
```

I'm still not happy with the overall precedence rules. It seems like no matter what I choose, it still will still confuse people.

**Comment by whitequark** [comment]
```
> 'a'/'b'/'c'
1 a c / b
```
I'm also unhappy with this... I almost think there should be a configuration option, but that will just backfire if I ever use the web version or a fresh install.

What does W|A do?

**Comment by tiffany352** [comment]
a / b c, apparently.

I'm not really sure what you expect / to do, if not one of these.

Maybe I should put mathjax higher up my todo list, because then it will be a lot clearer what rink is doing to your queries.

**Comment by whitequark** [comment]
> I'm not really sure what you expect / to do, if not one of these.

I'm expecting `a / b c`, of course, which is how GNU Units works, and also the straightforward result from `/` and `*` having the same prededence and associativity as literally anything else.

> Maybe I should put mathjax higher up my todo list, because then it will be a lot clearer what rink is doing to your queries.

Doesn't help me a little bit since I'm using it almost exclusively from console.

**Comment by tiffany352** [comment]
It looks like GNU units has juxtaposition have higher precedence than * and /, and then * and / have the same precedence. I think I'll implement that.

```
You have: kg / m * s
You want: 
        Definition: 1 kg s / m
You have: kg / m s
You want: 
        Definition: 1 kg / m s
```

**Comment by whitequark** [comment]
That works for me, thanks!

**Comment by tiffany352** [comment]
I've changed precedence, hopefully for the last time. Incidentally, your previous issue about the `of` operator now works as intended.

```
> 'a'/'b'/'c'
1 a / b c
> 'a'/('b'/'c')
1 a c / b
> ('a'/'b')/'c'
1 a / b c
> 'a'/'b'*'c'
1 a c / b
> 'a'/'b' 'c'
1 a / b c
> density of milk * 10L
approx. 10.22874 kilogram (mass)
```

**Comment by whitequark** [comment]
Excellent!
