### ISSUE TITLE
Explicit multipication of negative numbers does a sum instead

### ISSUE THREAD

**Issue by kalebo** [tiffany352/rink-rs#9]
Perhaps it's just me, but I found the with explicit multiplication and negative numbers to seriously trip up my calculations. The following example should illustrate the problem.

---

The following calculations work as expected, yielding the correct sum or product with implicit multiplication:
```
> 3/4  -1
-0.25 (dimensionless)
> 3/4 ( -1)
-0.75 (dimensionless)
```
However when a users tries to use explicit multiplication to avoid wrapping the negative in parentheses:
```
 > 3/4 * -1
-0.25 (dimensionless)
```

This is very unintuitive and for me and probably for others. I would consider it a serious bug to silently eat an explicit operator for multiplication and instead perform a sum. What's more this is not the behavior of frink on which rink seems to be based.

**Comment by tiffany352** [comment]
There is an ambiguity between `a - b` where it could result in either `a - (b)` or `a (-b)`. I could possibly make it so that `-` is greedily consumed as part of a number literal to fix this, but that would still cause the other behavior when attempting to use `-` as a unary prefix operator on something other than a number, such as a unit, which could potentially be more confusing. Another solution would be to make `-` whitespace sensitive, by performing a separate tokenization depending on whether it has a trailing space.

That second part about the `*` getting eaten definitely is a bug, which I will fix.

**Comment by tiffany352** [comment]
Actually, I'm not getting that to reproduce locally. Are you on the latest version? 0.4 changed the precedence rules for `*` and `/`.

```
> 3/4 * -1
-0.75 (dimensionless)
```

**Comment by kalebo** [comment]
Yep, I was on 0.3.2 and upgrading fixed the issue! Thanks for responding so quickly!
